### ISSUE TITLE
Doesn't seem to work on Unity 2021.3 13f1 (Help Needed)

### ISSUE THREAD

**Issue by lazydevyo** [Unity-Technologies/DynamicResolutionSample#3]
Dynamic Resolution Enabled from HDRP quality settings.
Camera has Dynamic resolution ticked.
dynamic resolution type set to hardware, upscale filter set to fidelity FX
Script untouched and dropped in the main camera.
Uncommented  #define ENABLE_DYNAMIC_RESOLUTION_DEBUG, 
Shows: Enabled: false

**Comment by MattSutherlin** [comment]
Sorry to hear that!

What platform(s) are you testing against?  Are you testing standalone player builds?

I know that as of ~2 months ago this did work in 2021.3.9f1 so hopefully we're not looking at an engine regression, but as soon as I know your platforms I will pull down .13f and retest as a first step and then we'll take it from there.

**Comment by lazydevyo** [comment]
> Sorry to hear that!
> 
> What platform(s) are you testing against? Are you testing standalone player builds?
> 
> I know that as of ~2 months ago this did work in 2021.3.9f1 so hopefully we're not looking at an engine regression, but as soon as I know your platforms I will pull down .13f and retest as a first step and then we'll take it from there.

Sorry for the late reply. Yes, standalone windows. I downgraded back to unity 2019 because I had issues with my projects. the result is the same with the dynamic resolution. i wonder if I didn't set it up correctly.

**Comment by MattSutherlin** [comment]
No worries.  Even if it's a setup issue on your end that sounds like an opportunity to improve the documentation.

Have you tried other upscale filter options?  Do you have the Frame Timing Manager enabled in your player settings?

I won't have time to delve into this until next year, but when I do I'll grab your version, set up some tests, and see if I can figure out where this is going wrong.

**Comment by lazydevyo** [comment]
Frame Timing Stats? I don't seem to find any Frame Timing Manager option. Frame Timing Stats is enabled.

**Comment by MattSutherlin** [comment]
Have you tried any of the other upscale filter options?  They should all work, but it would be good to eliminate possible variables.  Otherwise I'm out of ideas without a better idea on your setup.  If there's anything else you think might be relevant that you can share that might be helpful.  And if you manage to get it working I would be very interested to hear what was necessary so we can look at possibly updating documentation.

**Comment by Wikator** [comment]
Hi, I'm having very similar, if not the same problem. I believe I did all of the necessary setup, and it still says Enabled: False in the debug window.
```
            // If either of these report zero it means the platform doesn't support dynamic resolution.
            if (FrameTimingManager.GetCpuTimerFrequency() == 0 || FrameTimingManager.GetGpuTimerFrequency() == 0)
            {
                PlatformSupported = false;
                SystemEnabled = false;
            }
```
I figured out that both of the checks return 0 here, but I'm using Windows build, and I believe it's supported.
However, the script is still working to at least some extent. The target frame rate succesfully scales down on slower computers.

**Comment by MattSutherlin** [comment]
Would you mind opening a new issue for it?  I'll tag it as potentially linked to this, but in case it's not the same I don't want to intertwine it with this thread too much.
