### ISSUE TITLE
Enabled: False in the debug window (HDRP)

### ISSUE THREAD

**Issue by Wikator** [Unity-Technologies/DynamicResolutionSample#6]
I'm new to the HDRP so it might be me just messing something up, but I have done everything mentioned in the README and documentation.
```
            // If either of these report zero it means the platform doesn't support dynamic resolution.
            if (FrameTimingManager.GetCpuTimerFrequency() == 0 || FrameTimingManager.GetGpuTimerFrequency() == 0)
            {
                PlatformSupported = false;
                SystemEnabled = false;
            }
```
I figured out that both of the checks return 0 here, but I'm using Windows build, and I believe it's supported.
However, the script is still working to at least some extent. The target frame rate succesfully scales down on slower computers.

**Comment by MattSutherlin** [comment]
Just to confirm, is it the editor in Windows or a standalone Windows player?  Which version of Unity are you testing against?

When you're seeing the script work to some extent is that as is or are you removing this conditional block for checking the timer frequencies?  If it's as is, can you try removing the code you've referenced and see if behavior starts to be inline with expectations?

**Comment by Wikator** [comment]
Yes, I'm testing in Windows standalone, version 2021.3.17f1

Script working to some extent turned out to be false, frames were locked at 60 per second in build, and I assumed that script was responsible for it. The reason for lock was vsync, my bad.

Removing the referenced code unfortunately did nothing.

![image](https://user-images.githubusercontent.com/102376424/217236082-c9897607-ac31-47ad-bed9-9acedc8817f2.png)

![image](https://user-images.githubusercontent.com/102376424/217236253-6367bbc9-6299-4dd5-a3ba-7630ea0e9ebc.png)

![image](https://user-images.githubusercontent.com/102376424/217236607-bd1ef8dd-cfa1-46d4-b7b5-5bfe460bf63d.png)

![image](https://user-images.githubusercontent.com/102376424/217236909-1f67bf06-f475-4093-8b9e-2f695946ab7a.png)

**Comment by Wikator** [comment]
I figured it out. Turns out that graphics API used by my game did not support dynamic resolution. I had to turn off auto graphics API in Player settings, and change it to Vulkan.
